/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate user
         * @description Login with username and password to obtain JWT token
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Successful login */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Authentication failed */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Simple health check endpoint
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Server is running */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all tasks
         * @description Retrieve list of all tasks (no authentication required)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of tasks */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create new task
         * @description Create a new task with script and configuration
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** @description Task script content */
                        script?: string;
                        /**
                         * Format: uuid
                         * @description Optional custom task ID
                         */
                        id?: string;
                        /** @description Optional task name */
                        name?: string;
                        /** @description JSON string of task data */
                        data?: string;
                        /** @description JSON string of capability schema */
                        capabilitiesSchema?: string;
                        /** @enum {string} */
                        type?: "deno" | "python";
                        /** @description JSON string of transitions array */
                        transitions?: string;
                        /** @description JSON string of dependency task IDs */
                        dependsOn?: string;
                        /** @enum {integer} */
                        status?: 0 | 1 | 2 | 3 | 4;
                        /** @description Artefact files to upload */
                        file?: string[];
                    };
                    "application/json": components["schemas"]["TaskCreate"];
                };
            };
            responses: {
                /** @description Task created successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - insufficient permissions */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get script library
         * @description Retrieve list of available scripts with metadata
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of scripts with metadata */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ScriptLibraryItem"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasktracker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get task statistics
         * @description Retrieve rolling statistics for task additions, completions, and failures (data retained for up to 1 day)
         */
        get: {
            parameters: {
                query?: {
                    /** @description Time window in minutes for statistics (default 5) */
                    minutes?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Task statistics for the specified time window */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskTrackerStats"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agenttracker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get agent statistics
         * @description Retrieve rolling statistics for connected agents based on IP addresses (data retained for up to 1 day)
         */
        get: {
            parameters: {
                query?: {
                    /** @description Time window in minutes for statistics (default 1440) */
                    minutes?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Agent statistics for the specified time window */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentTrackerStats"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transitiontracker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get transition statistics
         * @description Retrieve rolling statistics for transition evaluations and executions (data retained for up to 1 day)
         */
        get: {
            parameters: {
                query?: {
                    /** @description Time window in minutes for statistics (default 1440) */
                    minutes?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Transition statistics for the specified time window */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransitionTrackerStats"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get task for execution
         * @description Poll for an available task matching agent capabilities
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskGetRequest"];
                };
            };
            responses: {
                /** @description Task available for execution or empty object if no task available */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uri
                             * @description URL to task script
                             */
                            script?: string;
                            /**
                             * Format: uuid
                             * @description Task ID
                             */
                            id?: string;
                            /**
                             * @description Task type
                             * @enum {string}
                             */
                            type?: "deno" | "python";
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - insufficient permissions */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task ID */
                id: string;
            };
            cookie?: never;
        };
        /**
         * Get task details
         * @description Retrieve detailed information about a specific task
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Task ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Task details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - insufficient permissions */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Task not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete task
         * @description Delete a task and its artefacts
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Task ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Task deleted successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - insufficient permissions */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Task not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Update task
         * @description Update task properties (currently only status)
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Task ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskUpdate"];
                };
            };
            responses: {
                /** @description Task updated successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - insufficient permissions */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Task not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/tasks/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task ID */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept task for execution
         * @description Mark a task as accepted and change status to RUNNING
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Task ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Task accepted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - insufficient permissions */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Task not found or not in AWAITING status */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task ID */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark task as completed
         * @description Mark a running task as completed and optionally update its data
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Task ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["TaskCompleteRequest"];
                };
            };
            responses: {
                /** @description Task completed successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - insufficient permissions */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Task not found or not in RUNNING status */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/data": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task ID */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update task data
         * @description Merge additional data into an existing task's data object
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Task ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskDataUpdate"];
                };
            };
            responses: {
                /** @description Task data updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - insufficient permissions */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Task not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/failed": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task ID */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark task as failed
         * @description Mark a running task as failed
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Task ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Task marked as failed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - insufficient permissions */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Task not found or not in RUNNING status */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/clone": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task ID */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clone task
         * @description Create a copy of an existing task with new ID
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Task ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Task cloned successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - insufficient permissions */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Task not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scripts/agent{extension}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description File extension (.ts for TypeScript, .py for Python, or empty) */
                extension: ".ts" | ".py" | "";
            };
            cookie?: never;
        };
        /**
         * Get agent template
         * @description Retrieve agent runner template for the specified language
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description File extension (.ts for TypeScript, .py for Python, or empty) */
                    extension: ".ts" | ".py" | "";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Agent template script */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/typescript": string;
                        "application/javascript": string;
                        "text/x-python": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scripts/{filename_with_extension}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Filename with extension */
                filename_with_extension: string;
            };
            cookie?: never;
        };
        /**
         * Get static script template
         * @description Retrieve a templated static script
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Filename with extension */
                    filename_with_extension: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Static script template */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/typescript": string;
                        "application/javascript": string;
                        "text/x-python": string;
                    };
                };
                /** @description Script not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scripts/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task ID */
                uuid: string;
            };
            cookie?: never;
        };
        /**
         * Get task script
         * @description Retrieve the processed script for a task with dependency injection
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Task ID */
                    uuid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Task script with injected dependencies */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/typescript": string;
                        "application/javascript": string;
                        "text/x-python": string;
                    };
                };
                /** @description Task not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List sheets
         * @description Get list of available sheet names
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of sheet names */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string[];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sheet name */
                id: string;
            };
            cookie?: never;
        };
        /**
         * Get sheet data
         * @description Retrieve sheet schema and all rows
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Sheet name */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sheet data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SheetResponse"];
                    };
                };
                /** @description Sheet not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Invalid sheet name or internal error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheets/{id}/data": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sheet name */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upsert sheet data
         * @description Insert or update a row in the sheet
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Sheet name */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SheetData"];
                };
            };
            responses: {
                /** @description Data upserted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - insufficient permissions */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Invalid sheet name or data format */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheets/{id}/data/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sheet name */
                id: string;
                /** @description Row key */
                key: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete sheet row
         * @description Delete a row from the sheet by key
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Sheet name */
                    id: string;
                    /** @description Row key */
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Row deleted successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - insufficient permissions */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Invalid sheet name */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/artefacts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task ID */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload artefact
         * @description Upload a file artefact for a task
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Task ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description File to upload
                         */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description File uploaded successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArtefactUploadResponse"];
                    };
                };
                /** @description Task not found */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - insufficient permissions */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/artefacts/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task ID */
                id: string;
                /** @description Artefact filename */
                filename: string;
            };
            cookie?: never;
        };
        /**
         * Get artefact
         * @description Redirect to the artefact file
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Task ID */
                    id: string;
                    /** @description Artefact filename */
                    filename: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to artefact file */
                307: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Task or artefact not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete artefact
         * @description Delete an artefact file from a task
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Task ID */
                    id: string;
                    /** @description Artefact filename */
                    filename: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Artefact deleted successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - insufficient permissions */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Task or artefact not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artefacts/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Artefact file path */
                path: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete artefact file
         * @description Delete any artefact file by path
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Artefact file path */
                    path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description File deleted successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - insufficient permissions */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description File not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Task: {
            /**
             * Format: uuid
             * @description Unique task identifier
             */
            id: string;
            /** @description Optional human-readable task name */
            name?: string;
            /** @description Task script content */
            script: string;
            /**
             * @description Task status:
             *     * 0 - AWAITING (ready for execution)
             *     * 1 - RUNNING (being executed)
             *     * 2 - COMPLETED (finished successfully)
             *     * 3 - FAILED (finished with error)
             *     * 4 - PAUSED (not ready for execution)
             * @enum {integer}
             */
            status: 0 | 1 | 2 | 3 | 4;
            /** @description Arbitrary JSON data associated with the task */
            data: Record<string, never>;
            /** @description List of artefact filenames */
            artefacts: string[];
            /** @description List of task IDs this task depends on */
            dependsOn: string[];
            /** @description Array of timed status transitions for the task */
            transitions: {
                /** @description Array of status names where this transition is active */
                statuses: ("AWAITING" | "RUNNING" | "COMPLETED" | "FAILED" | "PAUSED" | "DELETED")[];
                /** @description JSON Schema that specifies additional task transition conditions */
                condition: Record<string, never>;
                /** @description Timing configuration for the transition */
                timing: {
                    /** @description How often to check (e.g., "1h", "30m", "1s") */
                    every?: string;
                    /**
                     * @description If true, evaluates synchronously on status entry
                     * @default false
                     */
                    immediate: boolean;
                };
                /**
                 * @description Status name to transition to
                 * @enum {string}
                 */
                transitionTo: "AWAITING" | "RUNNING" | "COMPLETED" | "FAILED" | "PAUSED" | "DELETED";
                /** @description Optional data mutations to apply (JSON Merge Patch) */
                dataMutations?: Record<string, never>;
            }[];
            /**
             * @description Execution environment type
             * @enum {string}
             */
            type: "deno" | "python";
            /** @description JSON Schema for agent capability requirements */
            capabilitiesSchema: Record<string, never>;
        };
        TaskCreate: {
            /**
             * Format: uuid
             * @description Optional custom task ID
             */
            id?: string;
            /** @description Optional human-readable task name */
            name?: string;
            /** @description Task script content */
            script: string;
            data?: string | Record<string, never>;
            capabilitiesSchema?: string | Record<string, never>;
            /**
             * @description Execution environment type
             * @enum {string}
             */
            type?: "deno" | "python";
            /** @description Array of timed status transitions for the task */
            transitions?: {
                /** @description Array of status names where this transition is active */
                statuses: ("AWAITING" | "RUNNING" | "COMPLETED" | "FAILED" | "PAUSED" | "DELETED")[];
                /** @description JSON Schema that specifies additional task transition conditions */
                condition: Record<string, never>;
                /** @description Timing configuration for the transition */
                timing: {
                    /** @description How often to check (e.g., "1h", "30m", "1s") */
                    every?: string;
                    /**
                     * @description If true, evaluates synchronously on status entry
                     * @default false
                     */
                    immediate: boolean;
                };
                /**
                 * @description Status name to transition to
                 * @enum {string}
                 */
                transitionTo: "AWAITING" | "RUNNING" | "COMPLETED" | "FAILED" | "PAUSED" | "DELETED";
                /** @description Optional data mutations to apply (JSON Merge Patch) */
                dataMutations?: Record<string, never>;
            }[];
            /** @description JSON string or array of dependency task IDs */
            dependsOn?: string[] | string;
            /**
             * @description Initial task status
             * @enum {integer}
             */
            status?: 0 | 1 | 2 | 3 | 4;
        };
        TaskUpdate: {
            /**
             * @description New task status
             * @enum {integer}
             */
            status?: 0 | 1 | 2 | 3 | 4;
        };
        TaskGetRequest: {
            /**
             * @description Agent type
             * @enum {string}
             */
            type: "deno" | "python";
            /** @description Agent capabilities for matching */
            capabilities?: Record<string, never>;
        };
        TaskCompleteRequest: {
            /** @description Result data to merge into task data */
            data?: Record<string, never>;
        };
        TaskDataUpdate: {
            /** @description Data to merge into task data */
            data?: Record<string, never>;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        LoginResponse: {
            /** @description JWT token for authentication */
            token?: string;
        };
        /** @description Arbitrary data with required 'key' property */
        SheetData: {
            /** @description Primary key for the row */
            key?: string;
        } & {
            [key: string]: unknown;
        };
        SheetResponse: {
            columns?: Record<string, never>[];
            rows?: unknown[][];
        };
        ArtefactUploadResponse: {
            /**
             * Format: uri
             * @description URL to access the artefact
             */
            url?: string;
            /**
             * Format: uri
             * @description Direct URL to the artefact file
             */
            directURL?: string;
        };
        Error: {
            /** @description Error message */
            error?: string;
        };
        TaskTrackerStats: {
            /** @description Number of tasks added in the time window */
            added?: number;
            /** @description Number of tasks completed in the time window */
            completed?: number;
            /** @description Number of tasks failed in the time window */
            failed?: number;
            /** @description Time window in minutes used for the statistics */
            windowMinutes?: number;
        };
        AgentTrackerStats: {
            /** @description Total number of unique agents ever seen */
            totalUniqueAgents?: number;
            /** @description Number of agents active in the time window */
            activeAgents?: number;
            agents?: {
                /** @description Agent ID */
                id?: string;
                /** @description Agent IP address */
                ip?: string;
                /**
                 * Format: int64
                 * @description Timestamp of last agent connection
                 */
                lastSeen?: number;
            }[];
            /** @description Time window in minutes used for the statistics */
            windowMinutes?: number;
        };
        TransitionTrackerStats: {
            /** @description Total number of transition evaluations in the time window */
            totalEvaluations?: number;
            /** @description Total time spent evaluating transitions in milliseconds */
            totalEvaluationTimeMs?: number;
            /** @description Number of successful transitions in the time window */
            successfulTransitions?: number;
            /** @description Statistics grouped by transition target status */
            transitionsByType?: {
                [key: string]: {
                    /** @description Number of transitions to this status */
                    count?: number;
                    /** @description Total evaluation time for transitions to this status in milliseconds */
                    totalTime?: number;
                };
            };
            /** @description Time window in minutes used for the statistics */
            windowMinutes?: number;
        };
        ScriptLibraryItem: {
            /** @description Script filename */
            filename: string;
            /** @description Human-readable script name */
            name?: string;
            /** @description JSON Schema for agent capabilities */
            capabilitiesSchema?: Record<string, never>;
            /** @description Suggested default data for the task */
            suggestedData?: Record<string, never>;
            /** @description Comments about the task */
            comments?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
